/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "tertiary-fixed": "#ffdcc6",
        tertiary: "#ffb786",
        "surface-container": "#201f1f",
        "outline-variant": "#424754",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",
        "inverse-primary": "#005ac2",
        "secondary-fixed": "#d8e2ff",
        "on-surface": "#e5e2e1",
        "on-secondary": "#182f59",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#c2c6d6",
        "surface-container-highest": "#353534",
        "on-secondary-fixed-variant": "#304671",
        "on-primary": "#002e6a",
        "tertiary-container": "#df7412",
        "on-primary-container": "#00285d",
        "secondary-container": "#304671",
        "surface-container-low": "#1c1b1b",
        error: "#ffb4ab",
        "on-secondary-container": "#9fb5e7",
        "surface-tint": "#adc6ff",
        secondary: "#b1c6f9",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#393939",
        "error-container": "#93000a",
        primary: "#adc6ff",
        "on-tertiary": "#502400",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#4d8eff",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb786",
        "secondary-fixed-dim": "#b1c6f9",
        "on-error-container": "#ffdad6",
        outline: "#8c909f",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-container": "#461f00",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "primary-fixed": "#d8e2ff",
        "surface-variant": "#353534",
        background: "#131313",
        "on-primary-fixed": "#001a42",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        quartz: "0 25px 50px -12px rgba(0,0,0,0.6)",
      },
    },
  },
  plugins: [],
};